# Generated by Django 5.1.4 on 2026-09-22 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('doctors', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['hold', 'confirmed'])), fields=('doctor', 'date', 'time'), name='unique_active_booking_slot'),
        ),
    ]
