# Generated by Django 5.1.4 on 2026-09-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['purpose', 'is_used', 'expires_at'], name='users_otp_purpose_a8990f_idx'),
        ),
    ]
